compatibility_date = "2024-05-04"
pages_build_output_dir = "./dist"
name = "js-rpc-web"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "CALC", service = "calc", environment = "production" },
  { binding = "BLOG", service = "blog", environment = "production" }
]

[dev]
port = 8787