compatibility_date = "2024-05-04"
name = "server"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "CALC", service = "calc" },
  { binding = "BLOG", service = "blog" }
]

[dev]
port = 8787