compatibility_date = "2024-05-04"
main = "./src/index.ts"
name = "blog"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "js-rpc-blog-app"
database_id = "c98266a9-b7d3-43fa-94c2-7aa54318a2a2" # replace it with your database id
migrations_dir = "drizzle/migrations"

[dev]
port = 8782